// src/app/contact/page.tsx
"use client"

import { zodResolver } from '@hookform/resolvers/zod'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import z, { type ZodType } from 'zod'
import { type ContactFormInputs } from '~components/Forms/ContactForm'
import { Button } from '~components/ui/button'
import { Input } from '~components/ui/input'
import { Textarea } from '~components/ui/textarea'
import useAlert from '~hooks/useAlert'

const schema: ZodType<ContactFormInputs> = z.object({
    name: z.string().nonempty({ message: 'Name is required' }),
    email: z.string().email(),
    message: z.string().max(250, { message: 'Message must be less than 250 characters' })
})

export default function Contact() {
    const [isLoading, setIsLoading] = useState(false);
    const { register, handleSubmit, watch, formState: { errors }, reset } = useForm<ContactFormInputs>({
        resolver: zodResolver(schema)
    });

    const { setAlert } = useAlert();

    const messageField = watch('message', '');

    const submitData = async (data: ContactFormInputs) => {
        setIsLoading(true);
        const { signal, abort } = new AbortController();

        const res = await fetch('/api/contact', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data),
            signal
        })

        if(res.ok) {

            setAlert(prev => ({ ...prev, show: true, message: 'Message sent successfully', type: 'success' }));
            reset();

        } else {

            setAlert(prev => ({ ...prev, show: true, message: 'Something went wrong', type: 'error' }))

        }

        setIsLoading(false);

        return () => {

            abort();

        }

    }

    return (
        <div className='flex flex-col items-center w-full py-8 px-4 md:px-32 mx-auto self-start'>
            <h1 className='text-3xl mb-2 text-center md:m-0 md:text-[3rem] leading-normal font-semibold'>Contact Me</h1>
            <p className='text-center font-medium md:text-left'>
                I&apos;m currently available for freelance work. If you have a project that you want to get started, think you need my help with something, or just fancy saying hey, then get in touch.
            </p>

            <form className='flex flex-col p-4 w-72 md:w-[30rem]' onSubmit={handleSubmit(submitData)}>
                <div className='flex flex-col my-[0.75rem] mx-0'>
                    <label htmlFor="name" className='mb-2 font-medium'>Name</label>
                    <Input type="text" id="name" {...register('name', {
                        required: true,
                    })} />
                    {errors.name && <span className='text-red-500'>{errors.name.message}</span>}
                </div>
                <div className='flex flex-col my-[0.75rem] mx-0'>
                    <label htmlFor="email" className='mb-2 font-medium'>Email</label>
                    <Input type="email" id="email" {...register('email', {
                        required: true,
                    })} />
                    {errors.email && <span className='text-red-500'>{errors.email.message}</span>}
                </div>
                <div className='flex flex-col my-[0.75rem] mx-0'>
                    <label htmlFor="message" className='mb-2 font-medium'>Message</label>
                    <Textarea id="message" rows={5} className='rounded-md' {...register('message', {
                        required: true,
                    })} />
                    <small className='font-medium mt-2'>{messageField.length}/250</small>
                    {errors.message && <span className='text-red-500'>{errors.message.message}</span>}
                </div>
                
                <Button loading={isLoading}>Submit</Button>
            </form>
        </div>
    )
}

// src/routes/contact/+page.svelte
<script lang="ts">
	import { Button } from "$components/ui/button";
	import Input from "$components/ui/input/input.svelte";
	import { Textarea } from "$components/ui/textarea";
	import { onMount } from "svelte";

	let name = $state("");
	let email = $state("");
	let message = $state("");
	let isSubmitting = $state(false);
	let submitStatus = $state<"success" | "error" | null>(null);
	let statusMessage = $state("");

	const API_URL = "http://localhost:8080";

	async function handleSubmit(event: Event) {
		event.preventDefault();

		isSubmitting = true;
		submitStatus = null;

		try {
			const response = await fetch(`${API_URL}/api/contact`, {
				method: "POST",
				headers: {
					"Content-Type": "application/json",
				},
				body: JSON.stringify({ name, email, message }),
			});

			if (response.ok) {
				submitStatus = "success";
				statusMessage = "Message sent successfully!";
				name = "";
				email = "";
				message = "";
			} else {
				submitStatus = "error";
				statusMessage = "Something went wrong. Please try again.";
			}
		} catch (error) {
			submitStatus = "error";
			statusMessage = "Failed to send message. Please try again later.";
		} finally {
			isSubmitting = false;
		}
	}
</script>

<svelte:head>
	<title>Contact | Chukwuma Okoroji</title>
</svelte:head>

<div class="flex flex-col items-center justify-center min-h-screen p-12">
	<div class="w-full max-w-2xl">
		<h1 class="text-4xl lg:text-6xl mb-8 font-semibold text-center">
			Get In Touch
		</h1>
		<p class="text-lg lg:text-xl mb-8 text-center text-muted">
			Have a project in mind? Let's work together!
		</p>

		<form onsubmit={handleSubmit} class="flex flex-col gap-4">
			<div>
				<Input
					type="text"
					bind:value={name}
					placeholder="Full Name"
					required
					class="w-full px-4 py-3 rounded-lg"
				/>
			</div>

			<div>
				<Input
					type="email"
					bind:value={email}
					placeholder="Email Address"
					required
					class="w-full px-4 py-3 rounded-lg"
				/>
			</div>

			<div>
				<Textarea
					bind:value={message}
					placeholder="Message"
					rows={10}
					required
					maxlength={500}
					class="w-full px-4 py-3 rounded-lg resize-none"
				></Textarea>
				<p class="text-sm text-muted mt-1">{message.length}/500</p>
			</div>

			{#if submitStatus}
				<div
					class="p-4 rounded-lg {submitStatus === 'success'
						? 'bg-green-100 text-green-800'
						: 'bg-red-100 text-red-800'}"
				>
					{statusMessage}
				</div>
			{/if}

			<Button
				type="submit"
				disabled={isSubmitting || message.length > 500}
				variant="secondary"
				class="px-8 py-3 self-center"
			>
				{isSubmitting ? "Sending..." : "Submit"}
			</Button>
		</form>
	</div>
</div>
