// src/components/resume-button.tsx
'use client';

import { ArrowDownTrayIcon } from '@heroicons/react/24/outline';
import { usePlausible } from 'next-plausible';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { Button } from './ui/button';

export const ResumeButton = () => {
	const plausible = usePlausible();
	const pathname = usePathname();

	// const btnText = 'View My Resume';
	const btnText = pathname === '/' ? 'Download CV' : 'View My Resume';

	const handleClick = () => {
		plausible('Resume Downloaded', {
			props: {
				btnLocation: pathname,
				btnText: btnText,
			},
		});
	};

	return (
		<Button
			size='lg'
			variant='accent'
			className='underline'
			onClick={handleClick}
			asChild
		>
			<Link
				href='/Chukwuma_Okoroji.pdf'
				rel='noopener'
				target='_blank'
				download
			>
				{btnText}
				<ArrowDownTrayIcon className='w-4 h-4 ml-2' />
			</Link>
		</Button>
	);
};

// src/components/resume-button.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { Button } from "$components/ui/button";
	import { ArrowDown } from "@lucide/svelte";

	let pathname = "/";
	onMount(() => {
		if (typeof window !== "undefined") {
			pathname = window.location.pathname;
		}
	});

	$: btnText = pathname === "/" ? "Download CV" : "View My Resume";

	function handleClick() {
		// Call Plausible if available (plausible.js exposes a global function)
		try {
			if (typeof (window as any).plausible === "function") {
				(window as any).plausible("Resume Downloaded", {
					props: {
						btnLocation: pathname,
						btnText,
					},
				});
			}
		} catch (e) {
			// ignore errors
			// console.warn('plausible unavailable', e);
		}
	}
</script>

<Button
	variant="link"
	href="/Chukwuma_Okoroji.pdf"
	rel="noopener noreferrer"
	target="_blank"
	download
	on:click={handleClick}
	aria-label={btnText}
>
	{btnText}
	<ArrowDown className="ml-2 size-4" />
</Button>

<style></style>
