// src/components/ui/button/button.svelte
<script lang="ts" module>
	import { cn, type WithElementRef } from "$lib/utils.js";
	import type {
		HTMLAnchorAttributes,
		HTMLButtonAttributes,
	} from "svelte/elements";
	import { type VariantProps, tv } from "tailwind-variants";

	export const buttonVariants = tv({
		base: "focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive inline-flex shrink-0 items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium outline-none transition-all focus-visible:ring-[3px] disabled:pointer-events-none disabled:opacity-50 aria-disabled:pointer-events-none aria-disabled:opacity-50 [&_svg:not([class*='size-'])]:size-4 [&_svg]:pointer-events-none [&_svg]:shrink-0",
		variants: {
			variant: {
				default:
					"bg-primary text-primary-foreground shadow-xs hover:bg-primary/90",
				destructive:
					"bg-destructive shadow-xs hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60 text-white",
				outline:
					"bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/90 dark:hover:text-foreground border",
				secondary:
					"bg-secondary text-secondary-foreground shadow-xs hover:bg-secondary/80",
				accent: "bg-accent text-accent-foreground shadow-xs hover:bg-accent/80",
				ghost: "hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50",
				link: "text-primary underline-offset-4 hover:underline",
			},
			size: {
				default: "h-9 px-4 py-2 has-[>svg]:px-3",
				sm: "h-8 gap-1.5 rounded-md px-3 has-[>svg]:px-2.5",
				lg: "h-10 rounded-md px-6 has-[>svg]:px-4",
				icon: "size-9",
				"icon-sm": "size-8",
				"icon-lg": "size-10",
			},
		},
		defaultVariants: {
			variant: "default",
			size: "default",
		},
	});

	export type ButtonVariant = VariantProps<typeof buttonVariants>["variant"];
	export type ButtonSize = VariantProps<typeof buttonVariants>["size"];

	export type ButtonProps = WithElementRef<HTMLButtonAttributes> &
		WithElementRef<HTMLAnchorAttributes> & {
			variant?: ButtonVariant;
			size?: ButtonSize;
		};
</script>

<script lang="ts">
	let {
		class: className,
		variant = "default",
		size = "default",
		ref = $bindable(null),
		href = undefined,
		type = "button",
		disabled,
		children,
		...restProps
	}: ButtonProps = $props();
</script>

{#if href}
	<a
		bind:this={ref}
		data-slot="button"
		class={cn(buttonVariants({ variant, size }), className)}
		href={disabled ? undefined : href}
		aria-disabled={disabled}
		role={disabled ? "link" : undefined}
		tabindex={disabled ? -1 : undefined}
		{...restProps}
	>
		{@render children?.()}
	</a>
{:else}
	<button
		bind:this={ref}
		data-slot="button"
		class={cn(buttonVariants({ variant, size }), className)}
		{type}
		{disabled}
		{...restProps}
	>
		{@render children?.()}
	</button>
{/if}

// src/components/common/Button.tsx
import React, { forwardRef } from 'react';
import clsx from 'clsx';
import Loading from './Loading';

type buttonVariant = 'regular' | 'outline' | 'ghost' | 'link';
type buttonSize = 'sm' | 'md' | 'lg';

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
    variant?: buttonVariant;
    size?: buttonSize;
    children: React.ReactNode;
    loading?: boolean;
}

const sizeClasses = {
    sm: 'px-2 py-1',
    md: 'px-4 py-2 text-sm',
    lg: 'px-5 py-3 text-base',
}

const variantClasses = {
    regular: 'bg-gray-900 text-white hover:bg-gray-900 hover:opacity-80 transition-opacity',
    outline: 'border border-gray-900 text-gray-900 hover:bg-gray-900 hover:text-white hover:opacity-80 transition-opacity',
    ghost: 'text-gray-900 hover:bg-gray-900 hover:text-white hover:opacity-80 transition-opacity',
    link: 'text-gray-900 hover:underline disabled:no-underline',
}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(({ className, size='md', variant='regular', children, loading, ...props }, ref) => {

    return (
        <button 
            ref={ref}
            className={clsx(
                'flex justify-center h-fit w-fit rounded-lg text-xs font-medium transition-all m-2',
                'disabled:cursor-not-allowed disabled:opacity-50',
                className,
                sizeClasses[size],
                variantClasses[variant],
            )}
        {...props}>
            {loading && <Loading />}
            <span className={clsx('transition', {
                'opacity-0': loading,
                'opacity-100': !loading,
            })}>
                {children}
            </span>
        </button>
    )
})

Button.displayName = 'Button';

export default Button;
